#! /bin/sh

(touch /var/run/mce/restored) && (rm -f /var/lib/mce/*) && [ -d $HOME/.mce ] && (cd $HOME/.mce; tar cf - .) | (cd /var/lib/mce; tar xf - .)
status=$?

if [ $status -ne 0 ]; then
        if [ -d $HOME/.mce ]; then
		status=2
	fi
else
	rm -rf $HOME/.mce
fi

exit $status
