#! /bin/sh
# Verify that the kernel LED support works

engine=lysti
enable=disable

LED_PATH_LYSTI_DIRECT=/sys/class/leds/lp5523
LED_PATH_LYSTI_DIRECT_R_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:r/brightness
LED_PATH_LYSTI_DIRECT_G_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:g/brightness
LED_PATH_LYSTI_DIRECT_B_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:b/brightness
LED_PATH_LYSTI_DIRECT_R_CURRENT=$LED_PATH_LYSTI_DIRECT:r/led_current
LED_PATH_LYSTI_DIRECT_G_CURRENT=$LED_PATH_LYSTI_DIRECT:g/led_current
LED_PATH_LYSTI_DIRECT_B_CURRENT=$LED_PATH_LYSTI_DIRECT:b/led_current

LED_PATH_LYSTI_ENGINE=/sys/class/i2c-adapter/i2c-2/2-0032
LED_PATH_LYSTI_ENGINE1_MODE=$LED_PATH_LYSTI_ENGINE/engine1_mode
LED_PATH_LYSTI_ENGINE1_LOAD=$LED_PATH_LYSTI_ENGINE/engine1_load
LED_PATH_LYSTI_ENGINE1_LEDS=$LED_PATH_LYSTI_ENGINE/engine1_leds

LYSTI_MASK_RGB=000011100

LYSTI_MODE_DISABLED=disabled
LYSTI_MODE_DIRECT=direct
LYSTI_MODE_LOAD=load
LYSTI_MODE_RUN=run

LYSTI_TEST_PATTERN=9d80400044ff45ff

RGB_LED_CURRENT=50
RGB_LED_BRIGHTNESS=127

lysti_disable()
{
	# disable engine 1
	printf $LYSTI_MODE_DISABLED > $LED_PATH_LYSTI_ENGINE1_MODE

	# turn off RGB leds
	printf 0 > $LED_PATH_LYSTI_DIRECT_R_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_G_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_B_BRIGHTNESS

	# set led current to 0
	printf 0 > $LED_PATH_LYSTI_DIRECT_R_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_G_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_B_CURRENT
}

lysti_enable_direct()
{
	lysti_disable

	# set led current
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_R_CURRENT
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_G_CURRENT
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_B_CURRENT

	# set brightness
	printf $RGB_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_R_BRIGHTNESS
	printf $RGB_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_G_BRIGHTNESS
	printf $RGB_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_B_BRIGHTNESS
}

lysti_enable()
{
	lysti_disable

	# set led current to 42
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_R_CURRENT
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_G_CURRENT
	printf $RGB_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_B_CURRENT

	# set engine 1 to load
	printf $LYSTI_MODE_LOAD > $LED_PATH_LYSTI_ENGINE1_MODE

	# set engine 1 to control the RGB leds
	printf $LYSTI_MASK_RGB > $LED_PATH_LYSTI_ENGINE1_LEDS

	# load test pattern to engine 1
	printf $LYSTI_TEST_PATTERN > $LED_PATH_LYSTI_ENGINE1_LOAD

	# enable engine 1
	printf $LYSTI_MODE_RUN > $LED_PATH_LYSTI_ENGINE1_MODE
}

# setup command line options
while ! [ $# -eq 0 ]; do
	case $1 in
	lysti)
		engine=${1}
		;;
	enable|disable)
		enable=${1}
		;;
	enable-direct)
		enable=enable_direct
		;;
#	--help)
#		usage
#		exit 0
#		;;
#	--version)
#		version
#		exit 0
#		;;
#	*)
#		usage
#		exit 1
#		;;
	esac
	shift
done

if [ x"$(pidof mce)" != x"" ]; then
	printf "Warning, MCE is running; "
	printf "this will most likely interfere with testing\n"
fi

${engine}_${enable}
