#! /bin/sh
# Verify that the kernel LED support works
program=verifybacklight
version=1.16

engine=lysti
enable=disable

LED_PATH_LYSTI_DIRECT=/sys/class/leds/lp5523
LED_PATH_LYSTI_DIRECT_CHANNEL0_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel0/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL1_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel1/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL2_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel2/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL3_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel3/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL4_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel4/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL5_BRIGHTNESS=$LED_PATH_LYSTI_DIRECT:channel5/brightness
LED_PATH_LYSTI_DIRECT_CHANNEL0_CURRENT=$LED_PATH_LYSTI_DIRECT:channel0/led_current
LED_PATH_LYSTI_DIRECT_CHANNEL1_CURRENT=$LED_PATH_LYSTI_DIRECT:channel1/led_current
LED_PATH_LYSTI_DIRECT_CHANNEL2_CURRENT=$LED_PATH_LYSTI_DIRECT:channel2/led_current
LED_PATH_LYSTI_DIRECT_CHANNEL3_CURRENT=$LED_PATH_LYSTI_DIRECT:channel3/led_current
LED_PATH_LYSTI_DIRECT_CHANNEL4_CURRENT=$LED_PATH_LYSTI_DIRECT:channel4/led_current
LED_PATH_LYSTI_DIRECT_CHANNEL5_CURRENT=$LED_PATH_LYSTI_DIRECT:channel5/led_current

LED_PATH_LYSTI_ENGINE=/sys/class/i2c-adapter/i2c-2/2-0032
LED_PATH_LYSTI_ENGINE3_MODE=$LED_PATH_LYSTI_ENGINE/engine3_mode
LED_PATH_LYSTI_ENGINE3_LOAD=$LED_PATH_LYSTI_ENGINE/engine3_load
LED_PATH_LYSTI_ENGINE3_LEDS=$LED_PATH_LYSTI_ENGINE/engine3_leds

RX51_LYSTI_MASK_BACKLIGHT=111100011
RM680_LYSTI_MASK_BACKLIGHT=111111000

# Default to RM-680
LYSTI_MASK_BACKLIGHT=$RM680_LYSTI_MASK_BACKLIGHT

LYSTI_MODE_DISABLED=disabled
LYSTI_MODE_DIRECT=direct
LYSTI_MODE_LOAD=load
LYSTI_MODE_RUN=run

LYSTI_TEST_PATTERN=9d80407f00000000

BACKLIGHT_LED_CURRENT=50
BACKLIGHT_LED_BRIGHTNESS=127

usage()
{
	printf "Usage: %s [OPTION]... [MODEL] [ENGINE] [COMMAND]\n" "$program"
	printf "Test functionality of the keyboard backlight;\n"
	printf "if no command is passed, an attempt to disable the \n"
	printf "backlight of the default LED controller ($engine)\n"
	printf "\n"
	printf "  --enable-pm-debug   enable use of backlight for "
	printf "PM debuging\n"
	printf "  --disable-pm-debug  disable use of backlight for "
	printf "PM debuging\n"
	printf "  --help              display this help and exit\n"
	printf "  --version           output version information and exit\n"
	printf "\n"
	printf "Valid commands are:\n"
	printf "  enable              enable the LED backlight engine\n"
	printf "  disable             disable the LED backlight engine\n"
	printf "  enable-direct       enable the LED backlight\n"
	printf "  disable-direct      disable the LED backlight\n"
	printf "\n"
	printf "Valid models are:\n"
	printf "  rm680 (*)\n"
	printf "  rx51\n"
	printf "\n"
	printf "Valid engines are:\n"
	printf "  lysti (*)\n"
	printf "\n"
	printf "(*) Default value\n"
}

version()
{
	printf "%s %s\n" "$program" "$version"
}

lysti_disable()
{
	# disable engine 3
	printf $LYSTI_MODE_DISABLED > $LED_PATH_LYSTI_ENGINE3_MODE

	# set brightness to 0
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL0_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL1_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL2_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL3_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL4_BRIGHTNESS
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL5_BRIGHTNESS

	# set led current to 0
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL0_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL1_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL2_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL3_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL4_CURRENT
	printf 0 > $LED_PATH_LYSTI_DIRECT_CHANNEL5_CURRENT
}

lysti_enable_direct()
{
	lysti_disable

	# set led current
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL0_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL1_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL2_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL3_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL4_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL5_CURRENT

	# set brightness
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL0_BRIGHTNESS
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL1_BRIGHTNESS
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL2_BRIGHTNESS
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL3_BRIGHTNESS
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL4_BRIGHTNESS
	printf $BACKLIGHT_LED_BRIGHTNESS > $LED_PATH_LYSTI_DIRECT_CHANNEL5_BRIGHTNESS
}

lysti_enable()
{
	lysti_disable

	# set led current
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL0_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL1_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL2_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL3_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL4_CURRENT
	printf $BACKLIGHT_LED_CURRENT > $LED_PATH_LYSTI_DIRECT_CHANNEL5_CURRENT

	# set engine 3 to load
	printf $LYSTI_MODE_LOAD > $LED_PATH_LYSTI_ENGINE3_MODE

	# set engine 3 to control the backlight leds
	printf $LYSTI_MASK_BACKLIGHT > $LED_PATH_LYSTI_ENGINE3_LEDS

	# load test pattern to engine 3
	printf $LYSTI_TEST_PATTERN > $LED_PATH_LYSTI_ENGINE3_LOAD

	# enable engine 3
	printf $LYSTI_MODE_RUN > $LED_PATH_LYSTI_ENGINE3_MODE
}

# setup command line options
while ! [ $# -eq 0 ]; do
	case $1 in
	rx51)
		LYSTI_MASK_BACKLIGHT=$RX51_LYSTI_MASK_BACKLIGHT
		;;
	rm680)
		LYSTI_MASK_BACKLIGHT=$RM680_LYSTI_MASK_BACKLIGHT
		;;
	lysti)
		engine=${1}
		;;
	enable|disable)
		enable=${1}
		;;
	enable-direct)
		enable=enable_direct
		;;
	--disable-pm-debug)
		# Old interface
		[ -f /sys/devices/platform/gpio-switch/sleep_ind/state ] && printf inactive > /sys/devices/platform/gpio-switch/sleep_ind/state

		# New interface
		if [ -f /sys/class/gpio/export ]; then
			echo 92 > /sys/class/gpio/export
			# This doesn't seem to be used anymore
			# echo out > /sys/class/gpio/gpio92/direction
			echo 0 > /sys/class/gpio/gpio92/value
			# This seems to reset the value back to 1
			# echo 92 > /sys/class/gpio/unexport
		fi
		;;
	--enable-pm-debug)
		# Old interface
		[ -f /sys/devices/platform/gpio-switch/sleep_ind/state ] && printf active > /sys/devices/platform/gpio-switch/sleep_ind/state

		# New interface
		if [ -f /sys/class/gpio/export ]; then
			echo 92 > /sys/class/gpio/export
			# This doesn't seem to be used anymore
			# echo out > /sys/class/gpio/gpio92/direction
			echo 1 > /sys/class/gpio/gpio92/value
			echo 92 > /sys/class/gpio/unexport
		fi
		;;
	--help)
		usage
		exit 0
		;;
	--version)
		version
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
	shift
done

if [ x"$(pidof mce)" != x"" ]; then
	printf "Warning, MCE is running; "
	printf "this will most likely interfere with testing\n"
fi

${engine}_${enable}
