# Configuration file for MCE - display and keyboard backlight
# brightness control paths
#
# Normally MCE locates display backlight control files by probing
# few standard places under sysfs. In case the control files are
# in non-standard directories or probing produces false positive
# hits, a hardware adaptation specific configuration file should
# be used to define alternative sets of paths to check before
# generic probing.

[Display]

# Semicolon separated list of directories that contain writable
# "brightness" and readable "max_brightness" files.
#BrightnessDirectory=/sys/devices/i2c-0/0-0036/leds/lm3533-lcd-bl

# In case the control files do not follow the "brightness" and
# "max_brightness" pattern, semicolon separated list of full paths
# can be defined. Note that BrightnessPath and MaxBrightnessPath
# lists must have equal number of entries.
#BrightnessPath=/sys/path/to/brightness_file
#MaxBrightnessPath=/sys/path/to/max_brightness_file

[KeyPad]

# Timeout before disabling keyboard backlight when unused
#
# Timeout in seconds, default 30
#BacklightTimeout=30

# Keypad type
#
# Sliding keyboard (default) remains dark in lockscreen
#Type=Slide
#
# Flip phone uses keyboard also for lockscreen navigation
#Type=Flip

# Semicolon separated list of directories that contain writable
# "brightness" and readable "max_brightness" files for
# keyboard backlight.
#BrightnessDirectory=/sys/class/leds/keyboard

# Semicolon separated list of file paths that can be used
# for binary type backlight control
# toggle backlight on / off by writing "0" / "1"
#BinaryBrightnessFile=/sys/keylight_ctrl/control

# Optionally toggle backlight on when charging
#EnableBacklightWhenCharging=true
