# Configuration file for MCE - Example display configuration

[Display]

# If display brightness control is in non-linear or contains values that
# should be avoided (e.g. too dim / bright), it is possible to constrain mce
# to use only a subset of values available at hardware level.

# For example: Use 9 step brightness with maximum value of 128
BrightnessMapping=0;16;32;48;64;80;96;112;128
