# Configuration file for MCE - Example sensor configuration

[Sensors]

# If sensors sw stack returns raw light sensor values instead of
# calibrated lux values, auto-brightness configuration is unlikely
# to behave as expected.

# If it is just a scaling issue, then it might be possible to remedy
# situation my multiplying sensor readings with a configured constant
# internally within mce.

# For example: divide ALS sensor readings by 25
AlsValueMultiplier=0.04
